import React from "react";
import {
  FileText,
  ListChecks,
  Cpu,
  Eye,
  Download,
  Trash2,
  FolderOpen,
} from "lucide-react";
// ⚠️ Adjust this path to point to your existing StatusBadge file
import { StatusBadge } from "../../../../components/ui/StatusBadge";

const FilesTable = ({ files, onDelete }) => (
  <div className="overflow-hidden rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800">
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900/40 text-left text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">
            <th className="px-5 py-3">File</th>
            <th className="px-5 py-3">Difficulty</th>
            <th className="px-5 py-3">Questions</th>
            <th className="px-5 py-3">Model</th>
            <th className="px-5 py-3">Created</th>
            <th className="px-5 py-3">Generated by</th>
            <th className="px-5 py-3 text-right">Actions</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-100 dark:divide-gray-700/60">
          {files.map((file) => {
            // Map 'medium' to 'intermediate' to match your existing StatusBadge config
            const difficultyValue =
              file.difficulty?.toLowerCase() === "medium"
                ? "intermediate"
                : file.difficulty?.toLowerCase();

            return (
              <tr
                key={file.id}
                className="hover:bg-gray-50 dark:hover:bg-gray-700/30 transition-colors"
              >
                <td className="px-5 py-3.5 max-w-xs">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="w-9 h-9 rounded-lg bg-green-50 dark:bg-green-900/30 flex items-center justify-center flex-shrink-0">
                      <FileText className="h-4 w-4 text-green-600 dark:text-green-400" />
                    </div>
                    <div className="min-w-0">
                      <p
                        className="font-medium text-gray-900 dark:text-white truncate"
                        title={file.file_name}
                      >
                        {file.file_name}
                      </p>
                      <p className="text-xs text-gray-500 dark:text-gray-400 truncate">
                        {file.exam_title}
                      </p>
                    </div>
                  </div>
                </td>
                <td className="px-5 py-3.5">
                  {/* Using your existing StatusBadge component */}
                  <StatusBadge
                    value={difficultyValue}
                    showDot={false}
                    className="text-[11px]"
                  />
                </td>
                <td className="px-5 py-3.5 text-gray-700 dark:text-gray-300">
                  <span className="inline-flex items-center gap-1.5">
                    <ListChecks className="h-3.5 w-3.5 text-gray-400" />
                    {file.question_count}
                  </span>
                </td>
                <td className="px-5 py-3.5 text-gray-700 dark:text-gray-300 whitespace-nowrap">
                  <span className="inline-flex items-center gap-1.5">
                    <Cpu className="h-3.5 w-3.5 text-gray-400" />
                    {file.llm_model}
                  </span>
                </td>
                <td className="px-5 py-3.5 text-gray-500 dark:text-gray-400 whitespace-nowrap">
                  {new Date(file.created_at).toLocaleDateString()}
                </td>
                <td className="px-5 py-3.5 text-gray-500 dark:text-gray-400 truncate max-w-[140px]">
                  {file.generated_by_name}
                </td>
                <td className="px-5 py-3.5">
                  <div className="flex items-center justify-end gap-1">
                    <a
                      href={file.file_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      title="View file"
                      className="p-1.5 rounded-lg text-gray-500 dark:text-gray-400 hover:text-green-600 dark:hover:text-green-400 hover:bg-green-50 dark:hover:bg-green-900/20 transition-colors"
                    >
                      <Eye className="h-4 w-4" />
                    </a>
                    <a
                      href={file.file_url}
                      download
                      title="Download file"
                      className="p-1.5 rounded-lg text-gray-500 dark:text-gray-400 hover:text-green-600 dark:hover:text-green-400 hover:bg-green-50 dark:hover:bg-green-900/20 transition-colors"
                    >
                      <Download className="h-4 w-4" />
                    </a>
                    <button
                      onClick={() => onDelete(file.id)}
                      title="Delete file"
                      className="p-1.5 rounded-lg text-gray-500 dark:text-gray-400 hover:text-red-600 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  </div>
);

const EmptyFilesState = () => (
  <div className="flex flex-col items-center justify-center text-center p-12 rounded-2xl border border-dashed border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
    <div className="w-14 h-14 rounded-full bg-gray-100 dark:bg-gray-700 flex items-center justify-center mb-4">
      <FolderOpen className="h-7 w-7 text-gray-400" />
    </div>
    <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">
      No generated files yet
    </h3>
    <p className="text-xs text-gray-500 dark:text-gray-400 max-w-xs">
      Files you generate will show up here, ready to view, download, or remove.
    </p>
  </div>
);

export { FilesTable, EmptyFilesState };
